name: .NET

on:
  push:
    branches: [ master ]
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7  # v5.2.0
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test (net8.0)
      run: dotnet test --no-build --verbosity normal --framework net8.0 --logger "junit;LogFilePath=test-results/{assembly}.net8.0.xml"
      env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    - name: Test (net10.0)
      run: dotnet test --no-build --verbosity normal --framework net10.0 --logger "junit;LogFilePath=test-results/{assembly}.net10.0.xml"
      env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    - name: TestGlance
      if: always()
      uses: testglance/action@de3dd79416e362b938d22d66eeb4e5c89befad07  # v1
      with:
        github-token: ${{ github.token }}
